DROP TABLE IF EXISTS `registered_users`;
CREATE TABLE `registered_users` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `first_name` VARCHAR(32) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `zip` VARCHAR(32) NOT NULL,
  `phone` VARCHAR(32) NOT NULL,
  `reg_date` CHAR(8) NOT NULL,
  `time_stamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;